from math import sqrt
print("Program to calculate x from a quadratic formula (2nd degree equation)\n")
print("The quadratic formula is defined by ax^2 + bx + c = 0, where a is different from 0. So:")
a = int(input("Type the value of a: "))
b = int(input("Type the value of b: "))
c = int(input("Type the value of c: "))
x1 = (-b + sqrt((b**2) - (4*a*c)))/(2*a)
x2 = (-b - sqrt((b**2) - (4*a*c)))/(2*a)
print("\nThe values of the roots x of this equation are {:.2f} and {:.2f}.\n".format(x1, x2))
print("--- End of program. ---")
